[package]
name = "script"
version = "0.1.0"
edition = "2021"

[dependencies]
sp1-sdk = "4.2.1"
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
sp1-build = "4.2.1"
bincode = "1.3.3"

[build-dependencies]
sp1-build = "4.2.1"